# Generated by Django 5.0.2 on 2025-09-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='location',
        ),
        migrations.AddField(
            model_name='agent',
            name='profilepic',
            field=models.ImageField(default=1, upload_to='uploads/agentprofiles/'),
        ),
    ]
