# Generated by Django 5.0.2 on 2025-09-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_agent_location_agent_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='image',
            new_name='imageID',
        ),
    ]
