# Generated by Django 5.0.2 on 2025-09-06 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_image_agent_imageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='property',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='nav_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='property',
            name='pictures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='selrent',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.FloatField(null=True),
        ),
    ]
