# Generated by Django 5.0.2 on 2025-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_property_picture_remove_property_upload_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='nav_video',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pictures',
        ),
        migrations.AddField(
            model_name='property',
            name='picture',
            field=models.ImageField(default=1, upload_to='uploads/properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='location', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='selrent',
            field=models.CharField(default='rent/sell', max_length=50),
        ),
    ]
