# Generated by Django 5.0.2 on 2025-09-06 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_property_nav_video_remove_property_pictures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/properties/album/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='Home.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('picture', models.ImageField(default=1, upload_to='uploads/properties/')),
                ('description', models.TextField(max_length=2000)),
                ('size', models.FloatField(null=True)),
                ('bedrooms', models.FloatField(null=True)),
                ('bathrooms', models.FloatField(null=True)),
                ('location', models.CharField(default='location', max_length=100)),
                ('selrent', models.CharField(default='rent/sell', max_length=50)),
                ('nav_video', models.FileField(blank=True, null=True, upload_to='uploads/properties/videos/')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.property')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.type')),
            ],
        ),
    ]
