# Generated by Django 5.0.2 on 2025-09-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_propertyalbum_propertydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='nav_video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/properties/videos/'),
        ),
        migrations.DeleteModel(
            name='PropertyDetail',
        ),
    ]
