# Generated by Django 5.2.6 on 2025-09-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_property_nav_video_delete_propertydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='imageID',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/agents/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/agentprofiles/'),
        ),
    ]
